services:
  gerico-server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '5000:5000'
    restart: unless-stopped
